Make hashing a `RDN.Attribute.Value.utf8String` not allocate
apple/swift-certificates pull request #112
Opened 2023-07-11 16:24 UTC by dnadoba

### Motivation
Hashing a `RDN.Attribute.Value.utf8String` currently serialises the string to a temporary `Array`. This more than doubles allocations done during verification (allocation test not yet merged: https://github.com/apple/swift-certificates/pull/111)

### Modifications
Implement a  `String.ASN1UTF8StringView` that supports lazy iteration of the DER encoded bytes.

### Results
Allocations are reduce from ~1590 to ~660 in the allocation test introduced in #111 

`RDN.Attribute.Value.printable` will follow in a separate PR.

2023-07-17 14:50 UTC, Lukasa requested changes
A few notes, but also: when is this called on the verification path?

2023-07-17 14:50 UTC, Lukasa commented on Sources/X509/RDNAttribute.swift
> +    }
Can we compute this ahead of time? No need to recompute it each time we calculate `endIndex`.

2023-07-17 14:50 UTC, Lukasa commented on Sources/X509/RDNAttribute.swift
> +        let length = ASN1Length(length: self.string.utf8.count)
Similarly, let's precompute this to avoid repeatedly recalculating it.

2023-07-17 14:50 UTC, Lukasa commented on Sources/X509/RDNAttribute.swift
> +        precondition(position >= 0 && position < self.length)
Presumably here `position` was supposed to be less than `count`, not `length`?

2023-07-17 14:50 UTC, Lukasa commented on Sources/X509/RDNAttribute.swift
> +        }
We can precompute this too.

2023-07-18 15:39 UTC, dnadoba commented
Good catches! Applied them in https://github.com/apple/swift-certificates/pull/112/commits/dd1c74edbe48f4b0e54c386e2c4aabd54555fa0f
This is called for all root and intermediate certificates at least once because their subject name is used in `CertificateStore` as keys in the `Dictionary`. During verification the certificates issuer is looked up in the `CertificateStore`s which requires hashing of this again:
https://github.com/apple/swift-certificates/blob/c13badf75a49f052102188d4ca98cc15dc853f6f/Sources/X509/Verifier/Verifier.swift#L61

2023-07-20 08:59 UTC, Lukasa approved these changes

2023-07-20 08:59 UTC, merged