Allow OneOfPolicies and AllOfPolicies to take throwing policy builders, to match Verifier
apple/swift-certificates pull request #173
Opened 2024-05-07 14:30 UTC by hamzahrmalik

2024-05-07 15:07 UTC, dnadoba approved these changes
LGTM

2024-05-07 15:57 UTC, Lukasa requested changes
Can we add a test for this?

2024-05-17 10:59 UTC, FranzBusch approved these changes

2024-05-17 16:48 UTC, Lukasa approved these changes

2024-05-17 17:04 UTC, merged