Adds support for including signing time in signedAttrs for CMS signing.
apple/swift-certificates pull request #176
Opened 2024-05-29 20:05 UTC by R4N

Motivation:

Many CMS signing validations require the inclusion of signing time in signedAttrs (for example Apple Wallet's Pass CMS signing validation)

Modifications:

* Adds optional includeSigningTime flag to CMS.sign method (defaults to false)
* When includeSigningTime flag is true: includes signing-time (UTCTime ASN1Type), content-type, and message-digest signedAttrs and signs those instead of content bytes (as specified in RFC 5652 section 5.4)
* Adds contentType ASN1ObjectIdentifier
* Adds CMSSigningError (noTimeZone, invalidSigningDateComponent) for when includeSigningTime is true and unable to get UTC time zone or date components
* Adds tests for valid and invalid CMS signature when including signedAttrs

Result:

Providing the includeSigningTime = true flag to CMS.sign will cause signing-time, content-type, and message-digest signedAttrs to be included in the CMS signature and the signature bytes will represent signing those signedAttrs. Using CMS.sign without the flag (defaulting to false) should leave the previous CMS.sign behavior unchanged.

Resolves: https://github.com/apple/swift-certificates/issues/147

Submitted on behalf of Zetetic, LLC

2024-05-30 16:01 UTC, Lukasa requested changes
Thanks for this! I've left a few notes in the diff.

2024-05-30 16:01 UTC, Lukasa commented on Sources/X509/CryptographicMessageSyntax/CMSOperations.swift
> +            let nowComponents = calendar.dateComponents(desiredComponents, from: Date())
We should avoid this. We have a `Date.utcTime` transformation that already exists.

2024-05-30 16:11 UTC, dnadoba requested changes

2024-05-30 16:11 UTC, dnadoba commented on Sources/X509/CryptographicMessageSyntax/CMSOperations.swift
> +            try SHA256.hash(data: bytes).withUnsafeBytes { bufferPointer in
We should not need any unsafe Swift here. The returned digest conforms to `Sequence<UInt8>`. Just convert the returned bytes to an `ArraySlice`.

2024-05-30 16:12 UTC, dnadoba commented on Tests/X509Tests/CMSTests.swift
> +        try SHA256.hash(data: bytes).withUnsafeBytes { bufferPointer in
Also, here. No need for unsafe Swift.

2024-05-31 15:09 UTC, R4N commented
Thanks for the review/feedback. Definitely good suggestions. Using Date.utcDate to construct the UTCTime from date components allows me to remove the previously defined `CMSSigningError`s as both of the defined errors were related to DateComponents construction.

2024-06-04 12:52 UTC, Lukasa commented on Sources/X509/CryptographicMessageSyntax/CMSOperations.swift
> +            return try signWithSigningTime(
Nit: we prefer to use explicit `self` in all places.

2024-06-04 12:52 UTC, Lukasa commented on Sources/X509/CryptographicMessageSyntax/CMSOperations.swift
> +        return try serializeSignedData(signedData)
Same nit here, prefer `self.`

2024-06-04 12:52 UTC, Lukasa commented on Sources/X509/CryptographicMessageSyntax/CMSOperations.swift
> +        return try serializeSignedData(signedData)
Same note on `self` here.

2024-06-04 14:13 UTC, R4N commented
Added in the explicit `self`'s for the internal methods calls within CMSOperations.

2024-06-07 13:16 UTC, Lukasa commented
@swift-server-bot test this please

2024-06-07 13:48 UTC, Lukasa commented
These failures aren't your fault, our allocation baselines have regressed. I'll update them.

2024-06-07 15:27 UTC, Lukasa commented
Feel free to rebase on to the new `main` branch.

2024-06-07 16:05 UTC, R4N commented
I believe that should fix it up with the rebase now.

2024-06-07 16:06 UTC, Lukasa commented
@swift-server-bot test this please

2024-06-20 14:47 UTC, R4N commented
Just rebased off of main for the latest commit that came in. The last `swift-server-bot` check had a failure because of the `CMS.sign` API method signature changing. I believe this is a false positive because of the optional `signingTime` [parameter addition](https://github.com/R4N/swift-certificates/blob/signing-time/Sources/X509/CryptographicMessageSyntax/CMSOperations.swift#L27). Let me know if anything else needs to be done on my end.

2024-06-21 09:41 UTC, Lukasa commented
@swift-server-bot test this please

2024-06-21 10:31 UTC, dnadoba approved these changes
LGTM. Thanks!

2024-06-21 10:38 UTC, merged

2024-06-21 10:38 UTC, Lukasa commented
Merging over the API breakage.

2024-06-21 10:39 UTC, dnadoba commented
Note that this is in theory an API breaking change as unapplied methods do not take default values into account:
```swift
// this fails to compile now but previously compiled successfully
let ref = CMS.sign(_:signatureAlgorithm:additionalIntermediateCertificates:certificate:privateKey:)
```
We can partially workaround this limitation by keeping the old signature and introducing an overload with the new parameter. The func with the old signature would just call into the new method. 
However, this only partially solves the source break as
```swift
// error: Ambiguous use of 'CMS.sign'
let ref = CMS.sign
```
now becomes ambiguous and fails to compile as well.

I personally think this is fine though. 
@Lukasa wdyt?

2024-06-21 10:42 UTC, Lukasa commented
Yeah I don't mind at all. These are also CMS functions so they're not guaranteed to be API stable, so this isn't very egregious.